version: '3.6'

services:
    nginx:
        container_name: appto-nginx
        image: nginx:1.15-alpine
        restart: unless-stopped
        expose:
            - '80'
        ports:
            - "8090:80"
        networks:
            - appto
        volumes:
            - .:/app:delegated
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    php:
        container_name: appto-php
        image: appto-php-fpm
        build:
            context: ""
            dockerfile: Dockerfile
        restart: unless-stopped
        expose:
            - '9000'
        ports:
            - "9090:9001"
        networks:
            - appto
        volumes:
            - .:/app:delegated
        env_file:
            - .env
        depends_on:
            - mysql

    mysql:
        container_name: appto-mysql
        image: mariadb:10.4
        restart: unless-stopped
        ports:
            - "3306:3306"
        networks:
            - appto
        environment:
            MYSQL_ROOT_PASSWORD: root

networks:
    appto:
        name: appto_net
