doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        url: '%env(resolve:DATABASE_URL)%'

#        charset: utf8mb4
#        default_table_options:
#            charset: utf8mb4
#            collate: utf8mb4_unicode_ci
#        logging:  true
#        profiling:  true

    orm:
        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:

            common:
                type: xml
                dir: "%kernel.project_dir%/src/Appto/Common/Infrastructure/Persistence/Doctrine/Mapping"
                prefix: Appto\Common\Domain
                is_bundle: false

            office:
                type: xml
                dir: "%kernel.project_dir%/src/Appto/Office/Infrastructure/Persistence/Doctrine/Entity/Mapping"
                prefix: Appto\Office\Domain
                is_bundle: false
